### ISSUE TITLE
Black configuration screen in VS 2017

### ISSUE THREAD

**Issue by sidewinder94** [TrimbleSolutionsCorporation/VSSonarQubeExtension#266] opened 2017-08-07 13:45 UTC
Hi,

When opening the Sonar -> configuration menu, the option page which is opened is solid black, which makes it impossible to configure the extension for VS 2017.

Visual studio version : 2017 Version 15.2 (26430.6) Release
VSSonarExtension version : 1.0

Thanks

**Comment by jmecosta** [comment] 2017-08-07 17:32
1.0 version is a bit behind?  Can you try with latest

**Comment by sidewinder94** [comment] 2017-08-07 17:43
This is apparently the latest on the VS gallery, know where I can find a new version ? Or do I need to build it from source ?

**Comment by jmecosta** [comment] 2017-08-08 14:43
Then it's 6.3.3
marketplace.visualstudio.com/items?itemName=JorgeManuelEstevesdaCosta.VSSonarExtension2017

Can you share what other extension you have installed?  I'm not aware of
any issues in 2017 so it might be some problems with other extension

**Comment by sidewinder94** [comment] 2017-08-08 15:04
Confirmed the Black options using the 6.3.3.
Installed extensions are :
- Productivity Power Tools
- Resharper 
- OzCode
- Microsoft Visual studio 2017 installer projects 

And I believe th rest of them was installed with Visual studio.

**Comment by jmecosta** [comment] 2017-08-08 19:07
Could you try to remove resharper? Just to confirm?  Pretty sure it's not
ozcode?

**Comment by sidewinder94** [comment] 2017-08-09 09:17
Tried, no effect.
I'm using a Dark Theme in VS if that has an influence.

**Comment by jmecosta** [comment] 2017-08-09 13:21
Ah ok, then that explains it. Can you try change the theme?

**Comment by sidewinder94** [comment] 2017-08-10 07:36
Tried, the options window is still solid black except the title bar.

**Comment by jmecosta** [comment] 2017-08-10 10:05
Can you past some pics?

**Comment by sidewinder94** [comment] 2017-08-10 11:45
Here you go, light theme and resharper deactivated : 
![capture](https://user-images.githubusercontent.com/3798576/29169021-186262ee-7dd2-11e7-9c4b-11e9507dbc68.PNG)

**Comment by sidewinder94** [comment] 2017-08-16 08:54
Hi, I installes the new version and checked it was displaying the new version in the extension list (6.3.4).

Still the black options window.

**Comment by jmecosta** [comment] 2017-08-16 18:47
i cant replicate this. ive already installed all your extensions and works with all themes. would it be possible to test this in a clean visual studio without anything installed? first you install sonar extension, and then all others you use to see if can find the one causing the incomptibility. this is my configuration:

Microsoft Visual Studio Enterprise 2017 
Version 15.2 (26430.14) Release
VisualStudio.15.Release/15.2.0+26430.14
Microsoft .NET Framework
Version 4.7.02053

Installed Version: Enterprise

Architecture Diagrams and Analysis Tools   00369-60000-00001-AA398
Microsoft Architecture Diagrams and Analysis Tools

Visual Basic 2017   00369-60000-00001-AA398
Microsoft Visual Basic 2017

Visual C# 2017   00369-60000-00001-AA398
Microsoft Visual C# 2017

Visual C++ 2017   00369-60000-00001-AA398
Microsoft Visual C++ 2017

Visual F# 4.1   00369-60000-00001-AA398
Microsoft Visual F# 4.1

Application Insights Tools for Visual Studio Package   8.6.00404.2
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.0.30503.0
ASP.NET and Web Tools 2017

ASP.NET Web Frameworks and Tools 2017   5.2.50303.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.0.30209.0
Azure App Service Tools v3.0.0

ClangFormat   1.0
Formats code by calling the clang-format executable.

Common Azure Tools   1.9
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

GhostDoc   5.5.17070.0
Generate XML Comments from your code, maintain clean and up-to-date documentation, produce help documentation in multiple formats, use intelligent source code Spell Checker in Visual Studio.

Google Test Adapter   1.0
Google Test Adapter adds support for the C++ test framework Google Test

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JavaScript UWP Project System   2.0
JavaScript UWP Project System

JetBrains ReSharper Ultimate 2017.1.3    Build 108.0.20170613.154143
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2017 JetBrains, Inc.

KofePackagePackage Extension   1.0
KofePackagePackage Visual Studio Extension Detailed Info

Merq   1.1.17-rc (cba4571)
Command Bus, Event Stream and Async Manager for Visual Studio extensions.

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.50131.1

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   Mono.Debugging.VisualStudio
Support for debugging Mono processes with Visual Studio.

Node.js Tools   1.3.50417.1
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   4.2.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

OpenCoverUISettings   1.0
Visual Studio Integration for OpenCover

OpenCppCoverage   1.0
See https://opencppcoverage.codeplex.com/ for more details

OzCode   1.0
Your road to Magical Debugging. http://www.oz-code.com

OzCodePackage Extension   1.0
OzCodePackage Visual Studio Extension Detailed Info

Sandcastle Help File Builder   SHFB
Visual Studio integration for the Sandcastle Help File Builder.
https://GitHub.com/EWSoftware/SHFB

SQL Server Data Tools   15.1.61702.140
Microsoft SQL Server Data Tools

TypeScript   2.2.2.0
TypeScript tools for Visual Studio

Visual C++ for Linux Development   1.0.6
Visual C++ for Linux Development

Visual Studio tools for CMake   1.0
Visual Studio tools for CMake

Visual Studio Tools for Universal Windows Apps   15.0.26430.06
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

WiX Toolset Visual Studio Extension   0.9.21.62588
WiX Toolset Visual Studio Extension version 0.9.21.62588
Copyright (c) .NET Foundation and contributors. All rights reserved.

VSSonarExtension   1.0
This is a visual studio extension to provide an interface to a Sonar server

Xamarin   4.5.0.486 (fec6f88)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin.Android SDK   7.3.1.2 (9dbc4c5)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   10.10.0.37 (ad35de4)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by sidewinder94** [comment] 2017-08-17 07:32
Confirmed that it worked in the experimental instance of VS 2017.

I'm now in teh process of activating all the extensions to try and see if one is interfering.

**Comment by sidewinder94** [comment] 2017-08-17 07:37
Ok, now this is weird.... I've activated all of the extensions I had on my main instance of VS on the experimental instance, and it still worked.....

But the options screen is still black on my main instance....

**Comment by sidewinder94** [comment] 2017-08-17 07:42
I didn't found which was the conflicting extension, but found a workaround.

I deactivated all of the other extensions, then ran VS with only VSSonarQubeExtension.

The configuration screen then loaded.

I then reactivated **all** the other extensions and it continued to work.

The load order of the extensions might be in cause, but since I know nearly nothing about VS extensions, I can't tell you any more.

Thanks for taking time though

**Comment by jmecosta** [comment] 2017-08-17 09:22
ok good you manage to workaound. i close the issue we were not able to find a reproducable method.

**Closed by jmecosta** 2017-08-17 09:22 UTC

**Comment by Mariachi1231** [comment] 2017-09-26 10:12
Hey, i have the same issue in VS2015 Community

**Comment by Mariachi1231** [comment] 2017-09-26 10:13
On Enterprise it works fine, but in community i get a black screen

**Comment by Mariachi1231** [comment] 2017-09-26 10:24
Okay, i have removed the resharper and it start working

**Comment by jmecosta** [comment] 2017-09-26 11:46
yes

**Comment by jmecosta** [comment] 2018-05-08 10:07
@casimo this extension does not depend on other extensions. and there is no theme, there is a theme for visual studio and depending on it it will adjust the colors to look ok according to that visual Theme, so black, black, blue, blue.

the dependency, it seems to be related with a external library http://mahapps.com/ that we use, and it seems resharper also uses it. so if those are using a different version then it might cause this. at least that is my suspicion. 

Unfortunately this is not something i can solve, unless i remove the dependency to that library. But then i would need to right my own custom styles and it would not make it  so K.I.S.S.
